apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankdemo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankdemo-service
  template:
    metadata:
      labels:
        app: bankdemo-service
    spec:
      containers:
        - name: bankdemo-service
          image: bankdemo-service
          imagePullPolicy: Never
          ports:
            - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  name: bankdemo-service
spec:
  selector:
    app: bankdemo-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7000
  type: NodePort
